
version: 2

sources:
  - name: databricks_catalog
    database: hive_metastore
    schema: dbt_ychristoffel
    tables:
      - name: raw_contracts

models:
    - name: contracts
      description: "Contracts table for Hiltermann"
      columns:
          - name: Id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: AccountId
            tests:
                - not_null
          - name: Contract_origination_data__c
            tests:
                - not_null
          - name: Debtor__c
          - name: Driver__c
          - name: RecordTypeId
            tests:
                - not_null
          - name: Administration__c
            tests:
                - not_null
          - name: Module__c
            tests:
                - not_null
          - name: Hiltermann_contract__c
          - name: FL_request_ID__c
            tests:
                - not_null
